# Generated by Django 5.2.7 on 2025-10-08 17:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('buyer_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('buyer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'chat_rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField()),
                ('sender_type', models.CharField(choices=[('buyer', 'Buyer'), ('admin', 'Admin'), ('staff', 'Staff')], default='buyer', max_length=10)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('media_url', models.CharField(blank=True, default=None, help_text='URL path to uploaded media file', max_length=500, null=True)),
                ('media_type', models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video')], default=None, help_text='Type of media: image or video', max_length=20, null=True)),
                ('media_filename', models.CharField(blank=True, default=None, help_text='Original filename of uploaded media', max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['room', '-created_at'], name='chat_messag_room_id_584819_idx'), models.Index(fields=['user_id', '-created_at'], name='chat_messag_user_id_790302_idx'), models.Index(fields=['is_read', 'sender_type'], name='chat_messag_is_read_9fe84c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_role', models.CharField(default='buyer', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('room', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='chat.chatroom')),
            ],
            options={
                'db_table': 'chat_sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['room', 'user_id'], name='chat_sessio_room_id_b9dcbd_idx'), models.Index(fields=['is_active', '-started_at'], name='chat_sessio_is_acti_ee245d_idx')],
            },
        ),
    ]
